name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 2'
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  pre-checks:
    name: init
    uses: ./.github/workflows/pre-checks.yml
    permissions:
      contents: read

  tests:
    name: test
    needs: pre-checks
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read

  extra-checks:
    name: extra
    needs: pre-checks
    uses: ./.github/workflows/extra-checks.yml
    permissions:
      contents: read

  publish:
    name: pub
    needs: [ tests, extra-checks ]
    if: |
      github.ref == 'refs/heads/main' &&
      github.repository == 'xann16/snowdrift' &&
      github.event_name == 'release'
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  docs:
    name: docs
    needs: publish
    if: |
      always() &&
      github.ref == 'refs/heads/main' &&
      ( needs.publish.result == 'success' || ( github.event_name != 'release' && needs.publish.result == 'skipped' ) )
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: write
