name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 2'
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  pre-checks:
    name: init
    uses: ./.github/workflows/pre-checks.yml

  extra-checks:
    name: xtra
    needs: pre-checks
    uses: ./.github/workflows/extra-checks.yml

  tests:
    name: test
    needs: pre-checks
    uses: ./.github/workflows/tests.yml
