name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 2'
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  pre-checks:
    name: init
    uses: ./.github/workflows/pre-checks.yml

  tests:
    name: test
    needs: pre-checks
    uses: ./.github/workflows/tests.yml

  extra-checks:
    name: extra
    needs: pre-checks
    uses: ./.github/workflows/extra-checks.yml

  publish:
    name: pub
    needs: [ tests, extra-checks ]
    if: ${{ github.event_name == 'release' }}
    uses: ./.github/workflows/publish.yml
    permissions:
      id-token: write
    secrets: inherit
