name: docs

on:
  workflow_call:

jobs:

  build-and-upload-docs:
    name: Build and upload docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup project dependencies
        uses: ./.github/actions/project-setup

      - name: Generate HTML documentation using Sphinx
        run: uv run sphinx-build -M html docs/source/ docs/build/

      - name: Provide redirection from dev on fresh release deployment
        if: ${{ github.event_name == 'release' }}
        run: |
          mkdir docs/build/html/dev
          cp docs/source/utils/redirect.html docs/build/html/dev/index.html
        shell: bash

      - name: Deploy documentation to GitHub Pages
        if: ${{ github.event_name == 'release' || github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: docs/build/html
          target-folder: ${{ github.event_name == 'release' && '.' || './dev' }}
          clean: ${{ github.event_name == 'release' }}
