name: extra-checks

on:
  workflow_call:

jobs:

  url-check:
    name: Verify URLs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout project code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: urlstechie/urlchecker-action@master
        with:
          file_types: .md,.rst,.py,.json,.yaml,.yml,.toml,.txt
          print_all: false
          verbose: true
          timeout: 7
          retry_count: 3
