name: extra-checks

on:
  workflow_call:

jobs:

  url-check:
    name: URL checks
    runs-on: ubuntu-latest
#    permissions:
#      contents: read
    steps:

      - name: Checkout project code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify URLs found in project files
        uses: urlstechie/urlchecker-action@master
        with:
          file_types: .md,.rst,.py,.json,.yaml,.yml,.toml,.txt
          print_all: false
          verbose: true
          timeout: 7
          retry_count: 3

  codeql-analysis:
    name: CodeQL analysis
    uses: actions/reusable-workflows/.github/workflows/codeql-analysis.yml@main
    with:
      languages: '["python","actions"]'
    permissions:
      actions: read
      contents: read
      security-events: write
